### ISSUE TITLE
error for command "hasura microservice open app"

### ISSUE THREAD

**Issue by SiddharthSavant18** [hasura/hello-python-flask#4]
` Getting  Getting  Getting  Getting  Getting  Getting  Gettingx Opening microservice failed error=[1025]` `Didn't find any enternal URLs`
`for microserivce 'app'. Check 'conf/routes.yaml'`
 `# TIP: add an external URL for this microserivce`
` $ hasura conf generate-route app >> conf/routes.yaml`
i haved followed the steps correctly ,still i'm getting this error .

**Comment by coco98** [comment]
@Savant92 Can you show us your `conf/routes.yaml` and also the output of `hasura microservices ls`?

**Comment by SiddharthSavant18** [comment]
@coco98 output of " hasura microservice ls"
`filestore          Running     filestore.hasura:80           http://filestore.feudal57.hasura-app.io`
`gateway            Running`
`platform-sync      Running`
`postgres           Running     postgres.hasura:5432`
`auth               Running     auth.hasura:80                http://auth.feudal57.hasura-app.io`
`data               Running     data.hasura:80                http://data.feudal57.hasura-app.io`
`le-agent           Running`
`sshd               Running`
`notify             Running     notify.hasura:80              http://notify.feudal57.hasura-app.io`
`session-redis      Running     session-redis.hasura:6379`
and for conf/routes.yaml please click on this link [https://github.com/Savant92/hello-python-flask/blob/master/conf/routes.yaml](url)

**Comment by coco98** [comment]
@Savant92 This was a bug in the hasura CLI which should have been fixed. Can you try updating your CLI and then running the `ms open` command again?

@shahidhk @arvi3411301 your comments?

**Comment by shahidhk** [comment]
@coco98 We have not encountered this elsewhere. My guess is `routes.yaml` did not have the correct entry at the time.

@Savant92 can you confirm if the issue is happening persistently?

**Comment by coco98** [comment]
@shahidhk I remember a `hasura ms open` bug going around on windows?

**Comment by coco98** [comment]
@Savant92 My understanding is that if you actually go to your app external URL everything works fine right? It's just that `ms open` is not working?

**Comment by shahidhk** [comment]
@coco98 Will check on windows and confirm

**Comment by SiddharthSavant18** [comment]
@shahidhk yes the issue has been happening persistently .

**Comment by SiddharthSavant18** [comment]
@coco98 ya that's correct . the command `ms open` is not working.

**Comment by shahidhk** [comment]
@Savant92 Have you set a default browser? What is the output of command? Can you post a screenshot? We are not able to reproduce this issue

Re-open with a screenshot if error is still happening after setting a default browser
